feat : NG_BACK_END-159
nrhirano/q2-homework-01 pull request #1
Opened 2022-01-18 02:10 UTC by nrhirano

#### 関連タスク
- [NG_BACK_END-159 【第1回スクール宿題】 (平野様)](https://nishio-pj.backlog.com/view/NG_BACK_END-159)

#### PR 概要
- Q2 第1回スクールの宿題です。

#### 相談したい項目・保留した項目
- なし

#### 参考資料
- なし

2022-01-19 01:34 UTC, EikoNakashima commented
macではビルドこけます。
windowsでは通りますでしょうか？

2022-01-19 01:56 UTC, EikoNakashima commented on Dockerfile
> +ENV PATH /usr/local/git/bin:$PATH
```suggestion
ENV PATH=/usr/local/git/bin:$PATH
```

`=`をつけた方が明示的かと思います。
つけなくても動きます。

2022-01-19 01:56 UTC, EikoNakashima commented on Dockerfile
> +WORKDIR PATH
```suggestion
WORKDIR $PATH
```

環境変数を使う場合は、`$PATH`もしくは`${PATH}`というように記載しないといけないはずです。

2022-01-19 02:22 UTC, EikoNakashima requested changes

2022-01-19 02:22 UTC, EikoNakashima commented on Dockerfile
> +COPY ["./go.mod /go.mod","./main.go /main.go",]
```suggestion
COPY ["./go.mod","./main.go", "/"]
```

COPYを1つのレイヤーで対応する場合は、このような書き方になります。
最後の引数の場所にに手前の2つがCOPYされます。

2022-01-19 02:23 UTC, EikoNakashima commented on Dockerfile
> +COPY ["./go.mod /go.mod","./main.go /main.go",]
元々の記載で何故動いたかは不明です。
ちなみに、こちらのwindows環境でも動きませんでした。

2022-01-19 02:28 UTC, A-ichi11 commented on Dockerfile
> +
`RUN go mod download`

こちらも足しましょう。

2022-01-20 01:47 UTC, GenkiHirano approved these changes
LGTM 🐱

2022-01-20 01:48 UTC, EikoNakashima approved these changes
LGTM❄️

2022-01-20 07:38 UTC, merged